# Ejercicios NumPy

Tras hacer tus propias pruebas con la teoría de NumPy, completa los siguientes ejercicios en orden

---
## Ejercicio 1

Antes de empezar a trabajar de verdad, tendrás que importar la librería de NumPy para poder trabajar con ella:

In [2]:
import numpy as np

---
## Ejercicio 2

Crea un array de **una dimensión** con los 10 valores que tu quieras y muéstralo por pantalla:

In [34]:
a1d = np.array([1,2,3,4,5,6,7,8,9,0])
print(a1d)

[1 2 3 4 5 6 7 8 9 0]


---
## Ejercicio 3

Crea un array de distinto nombre al anterior de **dos dimensiones** con los 3x3 valores que tu quieras y muéstrala por pantalla:

In [5]:
a2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
print(a2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


---
## Ejercicio 4

Crea un array de distinto nombre a los anteriores de **tres dimensiones** con los 2x2x2 valores que tu quieras y muéstrala por pantalla:

In [24]:
a3d = np.array(
    [
        [
            [1,2],
            [3,4]
        ],
        [
            [5,6],
            [7,8]
        ],
    ])
print(a3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


---
## Ejercicio 5

Muestra las dimensiones, el tamaño y la forma que tienen las tres matrices creadas anteriormente:

In [22]:
for x in (a1d, a2d, a3d):
    print("Dimensiones: ", x.ndim)
    print("Tipo: ", x.dtype)
    print("Tamaño: ", x.size)
    print("Forma: ", x.shape)

Dimensiones:  1
Tipo:  int32
Tamaño:  10
Forma:  (10,)
Dimensiones:  2
Tipo:  int32
Tamaño:  9
Forma:  (3, 3)
Dimensiones:  3
Tipo:  int32
Tamaño:  8
Forma:  (2, 2, 2)


---
## Ejercicio 6

Crea un array de una dimensión de tipo int8. En una de las posiciones pon el valor 1000. ¿Qué ocurre y porqué?

In [40]:
a1di8 = np.array([1,2,3,4,5,6,7,8,9,0], dtype=np.int8)
a1di8[9] = 1000
print(a1di8)
print(a1di8.dtype)

[  1   2   3   4   5   6   7   8   9 -24]
int8


---
## Ejercicio 7

Crea un array de dos dimensiones de tipo float128 y luego muestra su tipo por pantalla:

In [45]:
a2df128 = np.array([[1,2,3,4,5],[6,7,8,9,0]], dtype=np.float64)
print(a2df128)
print(a2df128.dtype)

[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]
float64


---
## Ejercicio 8

Crea un array con la tabla del 5 en una sola instrucción y muéstralo por pantalla:

In [51]:
mult = 5
am5 = np.arange(0, 10 * mult, mult)
print(am5)

[ 0  5 10 15 20 25 30 35 40 45]


---
## Ejercicio 9

Crea un array con 20 valores entre los números 1 y 2. Estos valores deben estar distribuídos de manera equitativa:

In [55]:
a1e2 = np.linspace(0, 1, 20)
print(a1e2)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


---
## Ejercicio 10

Crea una matriz de forma 2x3 y muéstrala por pantalla. A continuación cambia su forma a una matriz 3x2

In [60]:
a2x3 = np.array([
    [1,2,3],
    [4,5,6]
    ])

a3x2 = a2x3.reshape(3, 2)

print(a2x3.shape)
print(a2x3)
print(a3x2.shape)
print(a3x2)

(2, 3)
[[1 2 3]
 [4 5 6]]
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


---
## Ejercicio 11

Crea una matriz de 3x6 con valores aleatorios. Después muestra por pantalla las siguientes convinaciones:
*   La primera fila entera
*   La primera columna entera
*   Todos los valores entre las columnas 2 y 4
*   Todos los valores de las filas 1 y 2
*   Todos los valores entre las filas 2 y 3 y las columnas 5 y 6

In [82]:
m3x6 = np.random.randint(10, size = (3, 6))

print(m3x6)
print("----------------")
print("1ª columna")
print(m3x6[0,:])
print("----------------")
print("1ª fila")
print(m3x6[:,0])
print("----------------")
print("Columas 2-4")
print(m3x6[:,1:4])
print("----------------")
print("Filas 1-2")
print(m3x6[0:2,:])
print("----------------")
print("Filas 2-3 Columnas 5-6")
print(m3x6[1:3,4:6])

[[8 6 7 3 5 2]
 [5 0 5 0 6 4]
 [1 1 7 0 3 3]]
----------------
Primera columna
[8 6 7 3 5 2]
----------------
Primera fila
[8 5 1]
----------------
Columas 2-4
[[6 7 3]
 [0 5 0]
 [1 7 0]]
----------------
Filas 1-2
[[8 6 7 3 5 2]
 [5 0 5 0 6 4]]
----------------
Filas 2-3 Columnas 5-6
[[6 4]
 [3 3]]


---
## Ejercicio 12

Crea un array de tamaño 1x5. Después añádele 5 elementos nuevos. Por último, elimina los dos primeros valores y muéstralo por pantalla:

In [85]:
a1x5 = np.array([1,2,3,4,5])
print(a1x5)
a1x5 = np.append(a1x5, [6,7,8,9,0])
print(a1x5)
a1x5 = np.delete(a1x5, [0,1])
print(a1x5)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8 9 0]
[3 4 5 6 7 8 9 0]


---
## Ejercicio 13

Crea dos matrices 3x3, una con valores aleatorios y otra de identidad. Realiza las cuatro operaciones básicas entre ellas (suma, resta, multiplicación y división). Por último, calcula la raíz cuadrada de matriz de identidad.

In [97]:
m1 = np.random.randint(10, size = (3,3))
m2 = np.identity(3)

print("Matriz1:")
print(m1)
print("-------------")
print("Matriz2:")
print(m2)
print("-------------")
print("Suma:")
print(m1 + m2)
print("-------------")
print("Resta:")
print(m1 - m2)
print("-------------")
print("Multiplicación:")
print(m1 * m2)
print("-------------")
print("División:")
print(m1 / m2)
print("-------------")
print("Raiz identidad:")
print(np.sqrt(m2))
print("-------------")

Matriz1:
[[9 8 5]
 [6 4 4]
 [4 3 5]]
-------------
Matriz2:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------
Suma:
[[10.  8.  5.]
 [ 6.  5.  4.]
 [ 4.  3.  6.]]
-------------
Resta:
[[8. 8. 5.]
 [6. 3. 4.]
 [4. 3. 4.]]
-------------
Multiplicación:
[[9. 0. 0.]
 [0. 4. 0.]
 [0. 0. 5.]]
-------------
División:
[[ 9. inf inf]
 [inf  4. inf]
 [inf inf  5.]]
-------------
Raiz identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------------


C:\Users\BDIA\AppData\Local\Temp/ipykernel_7812/351832289.py:20: RuntimeWarning: divide by zero encountered in true_divide
  print(m1 / m2)


---
## Ejercicio 14

Sin utilizar las funciones std, mean y median de NumPy, programa dichas funcionalidades:

In [110]:
matriz = np.random.randint(10, size = (3,3))

def calcMedia(matriz):
    media = float(np.sum(matriz) / matriz.size)
    return media

print(calcMedia(matriz))

5.666666666666667


---
## Ejercicio 15

Compara los tiempos de ejecución entre las funciones que has creado anteriormente  y las de NumPy para matrices de tamaño 1.000.000 x 1.000.000 con valores aleatorios: