---
Imports

In [31]:
import numpy as np
from Capa import Capa

---

Error Cuadrático Medio: $$ECM = 1/N * Σ_i^N(RE_i-RO_i)^2$$
derivada del Error Cuadrático Medio: $$dECM = 1/N * Σ_i^N(RE_i-RO_i)$$
derivada función Sigmoide: $$x * (1-x)$$
derivada función Hiperbólica: $$dtanhip = 1 - (tanhip(x)^2)$$
derivada función ReLu: $$f(x) = { 0, x <= 0; 1, x > 0}$$

In [42]:
class Red_Neuronal():
    def __init__(self,num_neuronas_capa, f_act_capa, num_inputs_1):
        self.lista_capas = []
        c = Capa(num_neuronas_capa[0], num_inputs_1, f_act_capa[0])
        self.lista_capas.append(c)
        for i in range(1, len(num_neuronas_capa)):
            c = Capa(num_neuronas_capa[i], num_neuronas_capa[i-1], f_act_capa[i])
            self.lista_capas.append(c)

    # Función para hacer los cálculos
    def calc(self, inputs):
        for c in self.lista_capas:
            inputs = c.get_output(inputs)
        return inputs

    # Función para entrenar
    def train(self, ratio):
        self.lista_capas[len(self.lista_capas)-1].peso_input # pesos
        # pesos = pesos - delta * pesos * ratio
        # bias = bias - delta * ratio

    def f_coste(self, r_esp, r_obt):
        ecm = pow((r_esp - r_obt).sum(), 2)/len(r_esp)
        return ecm

    # Función para mostrar los datos de la red neuronal
    def print(self):
        c = 1
        for capa in self.lista_capas:
            print("Capa c: ")
            capa.print()
            print("---------")
            c += 1

---
Pruebas

In [43]:
rn1 = Red_Neuronal([3,2,3], [4,2,3], 4)
# rn1.print()
res = rn1.calc([[4, -2, 3, -5]])
print(res)
print(rn1.f_coste(np.array([0.7, 0.6, 0.8]), res))
rn1.train(1)

[0.81818059 0.90625736 0.90877882]
0.09477337753381843
[[0.44897686 0.74716777 0.53109032]
 [0.1228664  0.1785211  0.67917733]
 [0.58241629 0.58410487 0.31893368]]
