# UT3 - Práctica 4

## Ejercicio 1

Antes de empezar a trabajar, tendrás que importar las librerías de NumPy y Matplotlib.Pyplot para poder trabajar con ellas:

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
## Ejercicio 2

Haz una función que, recibiendo una imagen en escala de grises (2D) como parámetro, devuelva un string con todas las intensidades de los píxeles de la imagen concatenadas en binario (utilizando 8 bits para cada píxel).

Por ejemplo, partiendo de una imagen como la siguiente:

        [[1 2 3]
        [4 5 6]
        [7 8 9]]

La función debería devolver la siguiente cadena de texto (sin espacios):

        00000001 00000010 00000011 00000100 00000101 00000110 00000111 00001000 00001001

In [29]:
def toBinary(matriz):
    lista = ""
    for fila in matriz:
        for columna in fila:
            b = bin(columna).replace("0b", "")
            while len(b) < 8:
                b = "0" + b
            lista += b
    return lista

matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(toBinary(matriz))

000000010000001000000011000001000000010100000110000001110000100000001001


---
## Ejercicio 3

Haz una función que, recibiendo una imagen en escala de grises (2D) como parámetro, devuelva un string similar al del ejercicio 2 solo que esta vez aplicando la redundancia de código. También deberá devolver la tabla donde muestre la relación entre cada intensidad y su código binario:

In [30]:
def redundancy(matriz):
    lista = ""
    y = 0
    valores = np.unique(matriz)
    tam = bin(len(valores)).replace("0b","")
    nums, valcod = {}, {}
    for x in valores:
        nums[x] = y
        y += 1
    for fila in matriz:
        for columna in fila:
            b = bin(nums[columna]).replace("0b", "")
            while len(b) < len(tam):
                b = "0" + b
            lista += " " + b
            valcod[columna] = b
    return valcod, lista

matriz = np.array([[1, 2, 3],[7, 8, 9],[1, 2, 3]])
tabla, lista = redundancy(matriz)
print(tabla)
print(lista)

{1: '000', 2: '001', 3: '010', 7: '011', 8: '100', 9: '101'}
 000 001 010 011 100 101 000 001 010


---
## Ejercicio 4

Haz una función que, recibiendo una imagen en escala de grises(2D) como parámetro, devuelva un string similar al del ejercicio 2 solo que esta vez aplicando la **codificación de Huffman**. También devolverá la tabla donde muestre la relación entre cada intensidad y su código binario:

In [87]:
def huffman(matriz):
    lista = ""
    valores = np.unique(matriz, return_counts=True)
    valcod, valprob = {}, {}
    y = 0

    # Sacar cuantas veces sale cada valor
    prob = valores[1]/np.sum(valores[1])

    # Asignar probabilidad de cada valor
    for x in valores[0]:
        valcod[x] = y
        valprob[x] = prob[y]
        y += 1

    # Ordenar el diccionario por probabilidad
    valprob = dict(sorted(valprob.items(), key=lambda x: x[1], reverse=True))

    # Árbol mágico para sacar las cosas
    listaprobs = list(valprob.values())
    dic = {}
    y = 0
    while len(listaprobs) > 1:
        valor = listaprobs[len(listaprobs)-1] + listaprobs[len(listaprobs)-2]
        listaotra = []
        listaotra.append("0")
        listaotra.append("1")
        listaotra.append(valor)
        listaotra.append(listaprobs[len(listaprobs)-1])
        listaotra.append(listaprobs[len(listaprobs)-2])
        dic[y] = listaotra
        y += 1
        listaprobs.pop(len(listaprobs)-1)
        listaprobs.pop(len(listaprobs)-1)
        listaprobs.append(valor)
        listaprobs.sort(reverse=True)
    
    # Árbol mágico inverso
    print("---", dic)
    while len(dic) >= 1:
        aux = dic[len(dic)-1]
        print(aux)
        dic.pop(len(dic)-1)
    return valcod, valprob, lista

matriz = np.array([[1, 2, 3],[2, 5, 6],[2, 3, 2]])
valcod, valprob, lista = huffman(matriz)
# print(valcod)
# print(valprob)
# print(lista)

--- {0: ['0', '1', 0.2222222222222222, 0.1111111111111111, 0.1111111111111111], 1: ['0', '1', 0.3333333333333333, 0.1111111111111111, 0.2222222222222222], 2: ['0', '1', 0.5555555555555556, 0.2222222222222222, 0.3333333333333333], 3: ['0', '1', 1.0, 0.4444444444444444, 0.5555555555555556]}
['0', '1', 1.0, 0.4444444444444444, 0.5555555555555556]
['0', '1', 0.5555555555555556, 0.2222222222222222, 0.3333333333333333]
['0', '1', 0.3333333333333333, 0.1111111111111111, 0.2222222222222222]
['0', '1', 0.2222222222222222, 0.1111111111111111, 0.1111111111111111]


In [75]:
# Huffman Coding in python

string = 'BCAADDDCCACACAC'


# Creating tree nodes
class NodeTree(object):

    def __init__(self, left=None, right=None):
        self.left = left
        self.right = right

    def children(self):
        return (self.left, self.right)

    def nodes(self):
        return (self.left, self.right)

    def __str__(self):
        return '%s_%s' % (self.left, self.right)


# Main function implementing huffman coding
def huffman_code_tree(node, left=True, binString=''):
    if type(node) is str:
        return {node: binString}
    (l, r) = node.children()
    d = dict()
    d.update(huffman_code_tree(l, True, binString + '0'))
    d.update(huffman_code_tree(r, False, binString + '1'))
    return d


# Calculating frequency
freq = {}
for c in string:
    if c in freq:
        freq[c] += 1
    else:
        freq[c] = 1

freq = sorted(freq.items(), key=lambda x: x[1], reverse=True)

nodes = freq

while len(nodes) > 1:
    (key1, c1) = nodes[-1]
    (key2, c2) = nodes[-2]
    nodes = nodes[:-2]
    node = NodeTree(key1, key2)
    nodes.append((node, c1 + c2))

    nodes = sorted(nodes, key=lambda x: x[1], reverse=True)

huffmanCode = huffman_code_tree(nodes[0][0])

print(' Char | Huffman code ')
print('----------------------')
for (char, frequency) in freq:
    print(' %-4r |%12s' % (char, huffmanCode[char]))

 Char | Huffman code 
----------------------
 'C'  |           0
 'A'  |          11
 'D'  |         101
 'B'  |         100


---
## Ejercicio 5

Importa una imagen y utiliza los tres métodos anteriores para codificarla. Finalmente, haz una comparación del tamaño resultante de cada una de ellas:

In [32]:
def colorToGrayscale2(img, r=0.2989, g=0.587, b=0.114):
    grayimg = img.copy()
    grayimg = (r*grayimg[:,:,0] + g*grayimg[:,:,1] + b*grayimg[:,:,2])/255 # Función para pasar rgb a grayscale
    return grayimg

In [33]:
img = colorToGrayscale2(plt.imread("01_kamina.jpg"))

binimg = toBinary(img)
plt.imshow(binimg)
plt.show()
redimg = redundancy(img)
plt.imshow(redimg)
plt.show()

TypeError: 'numpy.float64' object cannot be interpreted as an integer