# UT3 - Práctica 4

## Ejercicio 1

Antes de empezar a trabajar, tendrás que importar las librerías de NumPy y Matplotlib.Pyplot para poder trabajar con ellas:

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

---
## Ejercicio 2

Haz una función que, recibiendo una imagen en escala de grises (2D) como parámetro, devuelva un string con todas las intensidades de los píxeles de la imagen concatenadas en binario (utilizando 8 bits para cada píxel).

Por ejemplo, partiendo de una imagen como la siguiente:

        [[1 2 3]
        [4 5 6]
        [7 8 9]]

La función debería devolver la siguiente cadena de texto (sin espacios):

        00000001 00000010 00000011 00000100 00000101 00000110 00000111 00001000 00001001

In [2]:
def toBinary(matriz):
    lista = ""
    for fila in matriz:
        for columna in fila:
            b = bin(columna).replace("0b", "")
            while len(b) < 8:
                b = "0" + b
            lista += b
    return lista

matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(toBinary(matriz))

000000010000001000000011000001000000010100000110000001110000100000001001


---
## Ejercicio 3

Haz una función que, recibiendo una imagen en escala de grises (2D) como parámetro, devuelva un string similar al del ejercicio 2 solo que esta vez aplicando la redundancia de código. También deberá devolver la tabla donde muestre la relación entre cada intensidad y su código binario:

In [26]:
def redundancy(matriz):
    lista = ""
    y = 0
    valores = np.unique(matriz)
    tam = bin(len(valores)).replace("0b","")
    nums, valcod = {}, {}
    for x in valores:
        nums[x] = y
        y += 1
    for fila in matriz:
        for columna in fila:
            b = bin(nums[columna]).replace("0b", "")
            while len(b) < len(tam):
                b = "0" + b
            lista += " " + b
            valcod[columna] = b
    return valcod, lista

matriz = np.array([[1, 2, 3],[7, 8, 9],[1, 2, 3]])
tabla, lista = redundancy(matriz)
print(tabla)
print(lista)

{1: '000', 2: '001', 3: '010', 7: '011', 8: '100', 9: '101'}
 000 001 010 011 100 101 000 001 010


---
## Ejercicio 4

Haz una función que, recibiendo una imagen en escala de grises(2D) como parámetro, devuelva un string similar al del ejercicio 2 solo que esta vez aplicando la **codificación de Huffman**. También devolverá la tabla donde muestre la relación entre cada intensidad y su código binario:

In [79]:
def huffman(matriz):
    lista = ""
    valores = np.unique(matriz)
    veces = []
    nums, valcod, valprob = {}, {}, {}
    y = 0
    # Sacar cuantas veces sale cada valor
    for x in valores:
        veces.append(np.count_nonzero(matriz == x))
    prob = veces/np.sum(veces)
    # Asignar probabilidad de cada valor
    for x in valores:
        nums[x] = y
        valprob[x] = prob[y]
        y += 1
    valcod = nums
    # Ordenar el diccionario por probabilidad
    valprob = dict(sorted(valprob.items(), key=lambda x: x[1], reverse=True))
    # Árbol mágico para sacar las cosas
    listaprobs = list(valprob.values())
    print(len(listaprobs))
    while len(listaprobs) > 1:
        print(listaprobs)
        listaprobs.pop(len(listaprobs)-1)
    # while len > 1: sumar las probs menores y ordenar
    return valcod, valprob, lista

matriz = np.array([[1, 2, 3],[2, 5, 6],[2, 3, 2]])
valcod, valprob, lista = huffman(matriz)
print(valcod)
print(valprob)
print(lista)

5
[0.4444444444444444, 0.2222222222222222, 0.1111111111111111, 0.1111111111111111, 0.1111111111111111]
[0.4444444444444444, 0.2222222222222222, 0.1111111111111111, 0.1111111111111111]
[0.4444444444444444, 0.2222222222222222, 0.1111111111111111]
[0.4444444444444444, 0.2222222222222222]
{1: 0, 2: 1, 3: 2, 5: 3, 6: 4}
{2: 0.4444444444444444, 3: 0.2222222222222222, 1: 0.1111111111111111, 5: 0.1111111111111111, 6: 0.1111111111111111}



---
## Ejercicio 5

Importa una imagen y utiliza los tres métodos anteriores para codificarla. Finalmente, haz una comparación del tamaño resultante de cada una de ellas: